### ISSUE TITLE
0.6.5 integration

### ISSUE THREAD

**Issue by EricTheMagician** [meteorhacks/npm#7]
The npm package doesn't work with meteor 0.6.5

```
W20130816-16:52:02.338(-4)? (STDERR) Error: Cannot find module 'mandrill-api'
W20130816-16:52:02.338(-4)? (STDERR)     at Function.Module._resolveFilename (module.js:338:15)
W20130816-16:52:02.338(-4)? (STDERR)     at Function.Module._load (module.js:280:25)
W20130816-16:52:02.339(-4)? (STDERR)     at Module.require (module.js:362:17)
W20130816-16:52:02.339(-4)? (STDERR)     at require (module.js:378:17)
W20130816-16:52:02.339(-4)? (STDERR)     at Object._.each.Npm.require (/Users/ericyen/meteor/mailing-list/.meteor/local/build/programs/server/boot.js:86:18)
W20130816-16:52:02.339(-4)? (STDERR)     at Object.Meteor.require (packages/npm/index.js:4)
W20130816-16:52:02.339(-4)? (STDERR)     at app/server/startup.js:4:22
W20130816-16:52:02.340(-4)? (STDERR)     at mains (/Users/ericyen/meteor/mailing-list/.meteor/local/build/programs/server/boot.js:157:61)
W20130816-16:52:02.340(-4)? (STDERR)     at Array.forEach (native)
W20130816-16:52:02.342(-4)? (STDERR)     at Function._.each._.forEach (/Users/ericyen/.meteor/tools/4010e5731d/lib/node_modules/underscore/underscore.js:79:11)
=> Exited with code: 1
```

As soon as I downgrade back to 0.6.4.1, it works again.
